### ISSUE TITLE
开发是否完成？

### ISSUE THREAD

**Issue by yangangzhang** [micro-frontends-vue/final#2]
您好：
1. 开发测试完成了吗？
2. 相对于preload-routes，单个项目还是不可以启动本地开发？
3. 本地开发如何使用router 和store呢？
4. 单个项目的代理没有作用，必须配到到主项目中吗？

**Comment by zh-rocco** [comment]
@yangangzhang 

1. 最近忙着写业务代码，这个项目很久没更新了💔
2. 依然不可以单个项目本地开发
3. router、store 使用可以参考这里：[router](https://github.com/micro-frontends-vue/final/blob/master/applications/typescript/src/router.ts)、[store](https://github.com/micro-frontends-vue/final/blob/master/applications/typescript/src/store.ts)，跟普通项目并无区别
4. 暴露给浏览器访问的是主项目，所以 Proxy 需要在主项目内配置

**Comment by yangangzhang** [comment]
非常感谢您的回答，这个项目实际中使用有什么需要特别注意的吗？打算在项目中使用一下，正在权衡用这个final还是preload-routes

**Comment by zh-rocco** [comment]
@yangangzhang 

先说几个需要特别注意(坑)的地方:
1. 注意做子项目间的数据隔离(CSS 隔离, 自定义事件隔离, 全局变量隔离)
2. 项目间共享资源(components, utils, constants, scss/less variables)比较麻烦; components 可以注册为全局组件, utils 和 constants 可以挂载到 window 上, scss/less variables 只能拷贝(傻)或者通过 npm 包共享; 推荐使用 npm 包的形式共享资源
3. 暂时无法提取项目间的公共依赖
4. final 子项目间切换时会有白屏的问题(先跳路由, 然后再匹配、加载、渲染子项目导致的)
5. preload-routes 和 [async-routes](https://github.com/micro-frontends-vue/async-routes) 都是单 Vue 实例应用, 所有子项目必须使用同一个版本的 Vue, VueRouter, Vuex

final 还在完善中, 后面可能会有比较大的变更; 如果 preload-routes 满足需求的话, 个人比较推荐另外一个实现 [async-routes](https://github.com/micro-frontends-vue/async-routes), 做了子项目懒加载

这样改暂时不会出现什么问题, 在 render 函数里面实例化 Vue 是为了测试通过主项目注入 Vue, VueRouter, Vuex 的可行性

**Comment by yangangzhang** [comment]
> @yangangzhang
> 
> 先说几个需要特别注意(坑)的地方:
> 
> 1. 注意做子项目间的数据隔离(CSS 隔离, 自定义事件隔离, 全局变量隔离)
> 2. 项目间共享资源(components, utils, constants, scss/less variables)比较麻烦; components 可以注册为全局组件, utils 和 constants 可以挂载到 window 上, scss/less variables 只能拷贝(傻)或者通过 npm 包共享; 推荐使用 npm 包的形式共享资源
> 3. 暂时无法提取项目间的公共依赖
> 4. final 子项目间切换时会有白屏的问题(先跳路由, 然后再匹配、加载、渲染子项目导致的)
> 5. preload-routes 和 [async-routes](https://github.com/micro-frontends-vue/async-routes) 都是单 Vue 实例应用, 所有子项目必须使用同一个版本的 Vue, VueRouter, Vuex
> 
> final 还在完善中, 后面可能会有比较大的变更; 如果 preload-routes 满足需求的话, 个人比较推荐另外一个实现 [async-routes](https://github.com/micro-frontends-vue/async-routes), 做了子项目懒加载
> 
> 这样改暂时不会出现什么问题, 在 render 函数里面实例化 Vue 是为了测试通过主项目注入 Vue, VueRouter, Vuex 的可行性

**Comment by yangangzhang** [comment]
现在是用的final，preload或者async改动太大了，而且子项目中的store等都要加前缀，感谢您的回答！
