### ISSUE TITLE
请问大佬：子项目之间css冲突是怎么解决的

### ISSUE THREAD

**Issue by Enma19951007** [micro-frontends-vue/final#4]
您好大佬，现在我遇到了一个小问题。。就是有两个子项目（已完成） 现在使用这个框架合并在一起之后。样式有大量重复的名称，结果冲突了。想问有没有不改变子项目具体代码的方式解决这个问题（通过打包配置之类的），如果不行就算了。。希望大佬回复一下

**Comment by zh-rocco** [comment]
@Enma19951007 

可以试一下 [postcss-selector-namespace](https://github.com/topaxi/postcss-selector-namespace)

已知问题：
1. 增加 CSS 层级
2. 很难控制异步插入到 body 的 DOM 样式（如: ElementUI 的 $toast, $dialog 等）

**Comment by Enma19951007** [comment]
大佬说的很对。。算是解决了。。

安装
 npm install postcss-selector-namespace
直接在
package.json
  "postcss": {
    "plugins": {
      "autoprefixer": {},
      "postcss-selector-namespace": {
        "namespace": "#AppName"
      }
    }
  },
就可以了 AppName 我直接用的是   app.vue中的id
